/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class ArcNotes extends javax.swing.JFrame {

    /**
     * Creates new form ArcNotes
     */
    public ArcNotes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        VideosBtn = new javax.swing.JButton();
        PDFBtn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        computerALbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        VideosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Video.png"))); // NOI18N
        VideosBtn.setOpaque(false);
        VideosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VideosBtnMouseClicked(evt);
            }
        });
        VideosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideosBtnActionPerformed(evt);
            }
        });
        VideosBtn.setBounds(110, 450, 80, 40);
        jLayeredPane1.add(VideosBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PDFBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/PDF.png"))); // NOI18N
        PDFBtn.setOpaque(false);
        PDFBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFBtnActionPerformed(evt);
            }
        });
        PDFBtn.setBounds(210, 450, 80, 40);
        jLayeredPane1.add(PDFBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBtn.setOpaque(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        BackBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computerALbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        computerALbl.setForeground(new java.awt.Color(255, 255, 255));
        computerALbl.setText("Computer Arcitecture");
        computerALbl.setBounds(120, 80, 180, 70);
        jLayeredPane1.add(computerALbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arc.jpg"))); // NOI18N
        imageLbl.setBounds(10, 140, 280, 290);
        jLayeredPane1.add(imageLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        this.setVisible(false);
        CompNotes myNotes = new CompNotes();
        myNotes.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void VideosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideosBtnMouseClicked

        try {
            String URL = "www.youtube.com/channel/UCPrdwOI-MiGxAi_KWpTR8WA";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_VideosBtnMouseClicked

    private void VideosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideosBtnActionPerformed
    }//GEN-LAST:event_VideosBtnActionPerformed

    private void PDFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFBtnActionPerformed

        // resourced this code fom Stack overflow
        try {
            File pdf = new File("C:\\Users\\James Cosgrave\\Documents\\NetBeansProjects\\ComputingSupport - Copy\\src\\computingsupport\\ARC.pdf");
            Desktop.getDesktop().open(pdf);
        } catch (IOException ex) {
            Logger.getLogger(Programming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PDFBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArcNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArcNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArcNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArcNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArcNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton PDFBtn;
    private javax.swing.JButton VideosBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel computerALbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JButton jButton10;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
