/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class ComputingHome extends javax.swing.JFrame {

    /**
     * Creates new form ComputingHome
     */
    public ComputingHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JLayeredPane();
        NotesBtn = new javax.swing.JButton();
        GmailBtn = new javax.swing.JButton();
        FacebookBtn = new javax.swing.JButton();
        TwitterBtn = new javax.swing.JButton();
        NciBtn = new javax.swing.JButton();
        ContactBtn = new javax.swing.JButton();
        TimesBtn = new javax.swing.JButton();
        LocationBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        computingLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        feedbackBtn = new javax.swing.JButton();
        backgrounBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NotesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/notesBTN.png"))); // NOI18N
        NotesBtn.setBorder(null);
        NotesBtn.setOpaque(false);
        NotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesBtnActionPerformed(evt);
            }
        });
        NotesBtn.setBounds(150, 140, 130, 60);
        Home.add(NotesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        GmailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/goo.png"))); // NOI18N
        GmailBtn.setOpaque(false);
        GmailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GmailBtnMouseClicked(evt);
            }
        });
        GmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmailBtnActionPerformed(evt);
            }
        });
        GmailBtn.setBounds(150, 420, 50, 50);
        Home.add(GmailBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        FacebookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/fb.png"))); // NOI18N
        FacebookBtn.setOpaque(false);
        FacebookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacebookBtnMouseClicked(evt);
            }
        });
        FacebookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacebookBtnActionPerformed(evt);
            }
        });
        FacebookBtn.setBounds(80, 420, 50, 50);
        Home.add(FacebookBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TwitterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/tw.png"))); // NOI18N
        TwitterBtn.setOpaque(false);
        TwitterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwitterBtnMouseClicked(evt);
            }
        });
        TwitterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitterBtnActionPerformed(evt);
            }
        });
        TwitterBtn.setBounds(10, 420, 50, 50);
        Home.add(TwitterBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NciBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SU.png"))); // NOI18N
        NciBtn.setOpaque(false);
        NciBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NciBtnMouseClicked(evt);
            }
        });
        NciBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NciBtnActionPerformed(evt);
            }
        });
        NciBtn.setBounds(230, 420, 50, 50);
        Home.add(NciBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContactBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ContactBTN.png"))); // NOI18N
        ContactBtn.setOpaque(false);
        ContactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactBtnActionPerformed(evt);
            }
        });
        ContactBtn.setBounds(150, 210, 130, 60);
        Home.add(ContactBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TimesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/TimesBTN.png"))); // NOI18N
        TimesBtn.setOpaque(false);
        TimesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimesBtnActionPerformed(evt);
            }
        });
        TimesBtn.setBounds(10, 140, 130, 60);
        Home.add(TimesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LocationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ClassBTN.png"))); // NOI18N
        LocationBtn.setOpaque(false);
        LocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBtnActionPerformed(evt);
            }
        });
        LocationBtn.setBounds(10, 210, 130, 60);
        Home.add(LocationBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        Home.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        computingLbl.setForeground(new java.awt.Color(255, 255, 255));
        computingLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Comp.gif"))); // NOI18N
        computingLbl.setBounds(120, 100, 180, 40);
        Home.add(computingLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Register.png"))); // NOI18N
        registerBtn.setOpaque(false);
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        registerBtn.setBounds(70, 290, 140, 40);
        Home.add(registerBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        feedbackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Feedback.png"))); // NOI18N
        feedbackBtn.setOpaque(false);
        feedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackBtnActionPerformed(evt);
            }
        });
        feedbackBtn.setBounds(70, 360, 140, 40);
        Home.add(feedbackBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgrounBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgrounBtn.setBounds(0, 0, 300, 500);
        Home.add(backgrounBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesBtnActionPerformed
        this.setVisible(false);
        CompNotes myNotes = new CompNotes();
myNotes.setVisible(true);    }//GEN-LAST:event_NotesBtnActionPerformed

    private void TimesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimesBtnActionPerformed
        this.setVisible(false);
        CompTimes myTimes = new CompTimes();
        myTimes.setVisible(true);
    }//GEN-LAST:event_TimesBtnActionPerformed

    private void LocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBtnActionPerformed
        this.setVisible(false);
        Locations myLocations = new Locations();
        myLocations.setVisible(true);
    }//GEN-LAST:event_LocationBtnActionPerformed

    private void TwitterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwitterBtnActionPerformed

    private void ContactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactBtnActionPerformed
        this.setVisible(false);
        Contact myContact = new Contact();
        myContact.setVisible(true);
    }//GEN-LAST:event_ContactBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        this.setVisible(false);
        Registration myReg = new Registration();
        myReg.setVisible(true);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void feedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackBtnActionPerformed
        this.setVisible(false);
        Feedback myFeed = new Feedback();
        myFeed.setVisible(true);
    }//GEN-LAST:event_feedbackBtnActionPerformed

    private void TwitterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwitterBtnMouseClicked


        try {
            String URL = "www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_TwitterBtnMouseClicked

    private void FacebookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacebookBtnMouseClicked

try {
            String URL = "www.facebook.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_FacebookBtnMouseClicked

    private void GmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GmailBtnActionPerformed

    private void GmailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GmailBtnMouseClicked

try {
            String URL = "www.gmail.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_GmailBtnMouseClicked

    private void NciBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NciBtnMouseClicked


try {
            String URL = "www.ncisu.ie/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_NciBtnMouseClicked

    private void NciBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NciBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NciBtnActionPerformed

    private void FacebookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacebookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacebookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputingHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContactBtn;
    private javax.swing.JButton FacebookBtn;
    private javax.swing.JButton GmailBtn;
    private javax.swing.JLayeredPane Home;
    private javax.swing.JButton LocationBtn;
    private javax.swing.JButton NciBtn;
    private javax.swing.JButton NotesBtn;
    private javax.swing.JButton TimesBtn;
    private javax.swing.JButton TwitterBtn;
    private javax.swing.JLabel backgrounBtn;
    private javax.swing.JLabel computingLbl;
    private javax.swing.JButton feedbackBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
