/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

/**
 *
 * @author James Cosgrave
 */
public class Contact extends javax.swing.JFrame {

    private String EmailAddress;
    private String Email;
    private String Subject;
    private ContactEmail eArray[];
    private int count;

    public Contact() {
        initComponents();
        setLocationRelativeTo(null);
        EmailAddress = new String();
        Subject = new String();
        Email = new String();
        eArray = new ContactEmail[100];
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        backBtn = new javax.swing.JButton();
        contactLbl = new javax.swing.JLabel();
        supportLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        SendEmail = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jLabel5.setBackground(new java.awt.Color(204, 51, 0));

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contactLbl.setBackground(new java.awt.Color(255, 255, 255));
        contactLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        contactLbl.setForeground(new java.awt.Color(255, 255, 255));
        contactLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Contact.gif"))); // NOI18N
        contactLbl.setBounds(70, 100, 230, 29);
        jLayeredPane1.add(contactLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        supportLbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        supportLbl.setForeground(new java.awt.Color(255, 255, 255));
        supportLbl.setText("Computing Support Service");
        supportLbl.setBounds(20, 130, 280, 60);
        jLayeredPane1.add(supportLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        emailLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email: computingsupport@ncirl.ie");
        emailLbl.setBounds(20, 170, 270, 40);
        jLayeredPane1.add(emailLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        phoneLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneLbl.setForeground(new java.awt.Color(255, 255, 255));
        phoneLbl.setText("Phone: 01 6599260");
        phoneLbl.setBounds(120, 200, 170, 50);
        jLayeredPane1.add(phoneLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SendEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Send mail.png"))); // NOI18N
        SendEmail.setOpaque(false);
        SendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendEmailActionPerformed(evt);
            }
        });
        SendEmail.setBounds(20, 400, 250, 30);
        jLayeredPane1.add(SendEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        ComputingHome myHome = new ComputingHome();
        myHome.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void SendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendEmailActionPerformed
        this.setVisible(false);
        Email myEmail = new Email();
        myEmail.setVisible(true);
    }//GEN-LAST:event_SendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendEmail;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel supportLbl;
    // End of variables declaration//GEN-END:variables
}
