/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author Sam Gormley
 */
public class DisaHome extends javax.swing.JFrame {

    /**
     * Creates new form DisaHome
     */
    public DisaHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBTN = new javax.swing.JButton();
        contactBTN = new javax.swing.JButton();
        accessabilityBTN = new javax.swing.JButton();
        mapsBTN = new javax.swing.JButton();
        suBTN = new javax.swing.JButton();
        gmBTN = new javax.swing.JButton();
        twBTN = new javax.swing.JButton();
        fbBTN = new javax.swing.JButton();
        disabilityLbl = new javax.swing.JLabel();
        emailBTN = new javax.swing.JButton();
        backgroundBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBTN.setOpaque(false);
        homeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTNActionPerformed(evt);
            }
        });
        homeBTN.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(homeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contactBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ContactBTN.png"))); // NOI18N
        contactBTN.setOpaque(false);
        contactBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBTNActionPerformed(evt);
            }
        });
        contactBTN.setBounds(10, 220, 130, 60);
        jLayeredPane1.add(contactBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        accessabilityBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Acce.png"))); // NOI18N
        accessabilityBTN.setOpaque(false);
        accessabilityBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessabilityBTNActionPerformed(evt);
            }
        });
        accessabilityBTN.setBounds(160, 150, 130, 60);
        jLayeredPane1.add(accessabilityBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mapsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Maps.png"))); // NOI18N
        mapsBTN.setOpaque(false);
        mapsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapsBTNActionPerformed(evt);
            }
        });
        mapsBTN.setBounds(10, 150, 130, 60);
        jLayeredPane1.add(mapsBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        suBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SU.png"))); // NOI18N
        suBTN.setOpaque(false);
        suBTN.setBounds(240, 440, 50, 50);
        jLayeredPane1.add(suBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gmBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/goo.png"))); // NOI18N
        gmBTN.setOpaque(false);
        gmBTN.setBounds(160, 440, 50, 50);
        jLayeredPane1.add(gmBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        twBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/tw.png"))); // NOI18N
        twBTN.setOpaque(false);
        twBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twBTNMouseClicked(evt);
            }
        });
        twBTN.setBounds(80, 440, 50, 50);
        jLayeredPane1.add(twBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/fb.png"))); // NOI18N
        fbBTN.setOpaque(false);
        fbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbBTNMouseClicked(evt);
            }
        });
        fbBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbBTNActionPerformed(evt);
            }
        });
        fbBTN.setBounds(10, 440, 50, 50);
        jLayeredPane1.add(fbBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        disabilityLbl.setForeground(new java.awt.Color(255, 255, 255));
        disabilityLbl.setText("Disability");
        disabilityLbl.setBounds(160, 100, 190, 50);
        jLayeredPane1.add(disabilityLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        emailBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/samMail.png"))); // NOI18N
        emailBTN.setOpaque(false);
        emailBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBTNActionPerformed(evt);
            }
        });
        emailBTN.setBounds(160, 220, 130, 60);
        jLayeredPane1.add(emailBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundBtn.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTNActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBTNActionPerformed

    private void contactBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBTNActionPerformed
        this.setVisible(false);
        DisaContact myDContact = new DisaContact();
        myDContact.setVisible(true);
    }//GEN-LAST:event_contactBTNActionPerformed

    private void accessabilityBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessabilityBTNActionPerformed
        this.setVisible(false);
        Accessability myAccess = new Accessability();
        myAccess.setVisible(true);
    }//GEN-LAST:event_accessabilityBTNActionPerformed

    private void mapsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapsBTNActionPerformed
        this.setVisible(false);
        DisaMaps myDMaps = new DisaMaps();
        myDMaps.setVisible(true);
    }//GEN-LAST:event_mapsBTNActionPerformed

    private void emailBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBTNActionPerformed
        this.setVisible(false);
        DisaEmail myMail = new DisaEmail();
        myMail.setVisible(true);
    }//GEN-LAST:event_emailBTNActionPerformed

    private void fbBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fbBTNActionPerformed

    private void fbBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbBTNMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "www.facebook.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_fbBTNMouseClicked

    private void twBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twBTNMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_twBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisaHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessabilityBTN;
    private javax.swing.JLabel backgroundBtn;
    private javax.swing.JButton contactBTN;
    private javax.swing.JLabel disabilityLbl;
    private javax.swing.JButton emailBTN;
    private javax.swing.JButton fbBTN;
    private javax.swing.JButton gmBTN;
    private javax.swing.JButton homeBTN;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton mapsBTN;
    private javax.swing.JButton suBTN;
    private javax.swing.JButton twBTN;
    // End of variables declaration//GEN-END:variables
}
