/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class   Email extends javax.swing.JFrame implements Serializable {

    private String EmailAddress;
    private String Email;
    private String Subject;
    private ArrayList<ContactEmail> aList;
    private int count;

    /**
     *
     */
    public Email() {
        initComponents();
        setLocationRelativeTo(null);
        EmailAddress = new String();
        Subject = new String();
        Email = new String();
        aList = new ArrayList<>();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailPane = new javax.swing.JLayeredPane();
        EmailAddTF = new javax.swing.JTextField();
        fromLbl = new javax.swing.JLabel();
        SubjectTF = new javax.swing.JTextField();
        subjectLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmailTF = new javax.swing.JTextArea();
        SendBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        mathsBtn = new javax.swing.JButton();
        computingBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        emailLbl = new javax.swing.JLabel();
        sendEmailLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        EmailAddTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddTFActionPerformed(evt);
            }
        });
        EmailAddTF.setBounds(80, 190, 210, 30);
        EmailPane.add(EmailAddTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fromLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(255, 255, 255));
        fromLbl.setText("From:");
        fromLbl.setBounds(10, 190, 60, 30);
        EmailPane.add(fromLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SubjectTF.setBounds(80, 230, 210, 30);
        EmailPane.add(SubjectTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        subjectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subjectLbl.setForeground(new java.awt.Color(255, 255, 255));
        subjectLbl.setText("Subject:");
        subjectLbl.setBounds(10, 230, 70, 30);
        EmailPane.add(subjectLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EmailTF.setColumns(20);
        EmailTF.setRows(5);
        jScrollPane1.setViewportView(EmailTF);

        jScrollPane1.setBounds(10, 280, 280, 100);
        EmailPane.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Send.png"))); // NOI18N
        SendBtn.setOpaque(false);
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        SendBtn.setBounds(120, 390, 80, 40);
        EmailPane.add(SendBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Cancel.png"))); // NOI18N
        CancelBtn.setOpaque(false);
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        CancelBtn.setBounds(210, 390, 80, 40);
        EmailPane.add(CancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mathsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Maths.png"))); // NOI18N
        mathsBtn.setOpaque(false);
        mathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsBtnActionPerformed(evt);
            }
        });
        mathsBtn.setBounds(20, 450, 110, 30);
        EmailPane.add(mathsBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        computingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Computer.png"))); // NOI18N
        computingBtn.setOpaque(false);
        computingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computingBtnActionPerformed(evt);
            }
        });
        computingBtn.setBounds(160, 450, 130, 30);
        EmailPane.add(computingBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        EmailPane.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        emailLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email: Support@ncirl.ie");
        emailLbl.setBounds(20, 140, 270, 40);
        EmailPane.add(emailLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sendEmailLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sendEmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        sendEmailLbl.setText("Send Email");
        sendEmailLbl.setBounds(170, 90, 150, 60);
        EmailPane.add(sendEmailLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        EmailPane.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        EmailTF.setText("");
        SubjectTF.setText("");
        EmailAddTF.setText("");    }//GEN-LAST:event_CancelBtnActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed

        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("Email.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);
            JOptionPane.showMessageDialog(rootPane, "Your Email has been sent");

            oStream.close();

        } catch (IOException e) {
            System.out.print(e);


        }

        EmailAddress = EmailAddTF.getText();
        Subject = SubjectTF.getText();
        Email = EmailTF.getName();

        ContactEmail e = new ContactEmail();

        e.setEmail(Email);
        e.setSubject(Subject);
        e.setEmailAddress(EmailAddress);


        aList.add(e);
        count++;    }//GEN-LAST:event_SendBtnActionPerformed

    private void EmailAddTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddTFActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);    }//GEN-LAST:event_homeBtnActionPerformed

    private void mathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsBtnActionPerformed
        this.setVisible(false);
        MathsHome myContact = new MathsHome();
        myContact.setVisible(true);    }//GEN-LAST:event_mathsBtnActionPerformed

    private void computingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computingBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ComputingHome myComputing = new ComputingHome();
        myComputing.setVisible(true);
    }//GEN-LAST:event_computingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Email.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Email().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField EmailAddTF;
    private javax.swing.JLayeredPane EmailPane;
    private javax.swing.JTextArea EmailTF;
    private javax.swing.JButton SendBtn;
    private javax.swing.JTextField SubjectTF;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton computingBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mathsBtn;
    private javax.swing.JLabel sendEmailLbl;
    private javax.swing.JLabel subjectLbl;
    // End of variables declaration//GEN-END:variables
}
