/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.io.Serializable;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class Feedback extends javax.swing.JFrame implements Serializable {

    private String feedbackText;
    private String Name;
    private feedbackComments fArray[];
    private int count;

    public Feedback() {
        initComponents();
        setLocationRelativeTo(null);
        feedbackText = new String();
        Name = new String();
        fArray = new feedbackComments[100];
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FeedbackTF = new javax.swing.JTextPane();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Review = new javax.swing.JButton();
        BackBTN1 = new javax.swing.JButton();
        ContactDetailsLbl = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        commentsLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 70, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane2.setViewportView(FeedbackTF);

        jScrollPane2.setBounds(10, 250, 270, 120);
        jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Submit.png"))); // NOI18N
        Submit.setOpaque(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        Submit.setBounds(10, 400, 80, 40);
        jLayeredPane1.add(Submit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Clear2.png"))); // NOI18N
        Cancel.setOpaque(false);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        Cancel.setBounds(110, 400, 80, 40);
        jLayeredPane1.add(Cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Review.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Review.png"))); // NOI18N
        Review.setOpaque(false);
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });
        Review.setBounds(210, 400, 80, 40);
        jLayeredPane1.add(Review, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN1.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN1.setOpaque(false);
        BackBTN1.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTN1ActionPerformed(evt);
            }
        });
        BackBTN1.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContactDetailsLbl.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        ContactDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        ContactDetailsLbl.setText("Feedback");
        ContactDetailsLbl.setBounds(170, 120, 105, 30);
        jLayeredPane1.add(ContactDetailsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        NameTF.setBounds(10, 180, 270, 40);
        jLayeredPane1.add(NameTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        commentsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        commentsLbl.setForeground(new java.awt.Color(255, 255, 255));
        commentsLbl.setText("Comments:");
        commentsLbl.setBounds(10, 220, 100, 30);
        jLayeredPane1.add(commentsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setText("Name:");
        nameLbl.setBounds(10, 140, 80, 30);
        jLayeredPane1.add(nameLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        feedbackText = FeedbackTF.getText();
        Name = NameTF.getText();


        feedbackComments f = new feedbackComments();

        f.setFeedbackText(feedbackText);
        f.setName(Name);


        fArray[count] = f;

        count++;

    }//GEN-LAST:event_SubmitActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        for (int i = 0; i < count; i++) {
            JOptionPane.showMessageDialog(null, "Name: " + fArray[i].getName() + "\n Feedback: " + fArray[i].getFeedbackText());
        }


    }//GEN-LAST:event_ReviewActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);    }//GEN-LAST:event_homeBtnActionPerformed

    private void BackBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTN1ActionPerformed
        this.setVisible(false);
        ComputingHome myHome = new ComputingHome();
        myHome.setVisible(true);
    }//GEN-LAST:event_BackBTN1ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        FeedbackTF.setText("");
        NameTF.setText("");

    }//GEN-LAST:event_CancelActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN1;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel ContactDetailsLbl;
    private javax.swing.JTextPane FeedbackTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton Review;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel commentsLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLbl;
    // End of variables declaration//GEN-END:variables
}
