/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class LearnNotes extends javax.swing.JFrame {

    /**
     * Creates new form LearnNotes
     */
    public LearnNotes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        notesHeader = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();
        visualBtn = new javax.swing.JButton();
        auditoryBtn = new javax.swing.JButton();
        KinestheticBtn = new javax.swing.JButton();
        takeTheQuizBtn = new javax.swing.JButton();
        questionLbl = new javax.swing.JLabel();
        videoBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        notesHeader.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        notesHeader.setForeground(new java.awt.Color(255, 255, 255));
        notesHeader.setText("Notes");
        notesHeader.setBounds(190, 100, 80, 50);
        jLayeredPane1.add(notesHeader, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN.setOpaque(false);
        BackBTN.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        BackBTN.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        visualBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/VisualBtn.png"))); // NOI18N
        visualBtn.setOpaque(false);
        visualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualBtnActionPerformed(evt);
            }
        });
        visualBtn.setBounds(100, 260, 110, 40);
        jLayeredPane1.add(visualBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        auditoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/AuditoryBtn.png"))); // NOI18N
        auditoryBtn.setOpaque(false);
        auditoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditoryBtnActionPerformed(evt);
            }
        });
        auditoryBtn.setBounds(100, 210, 110, 40);
        jLayeredPane1.add(auditoryBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        KinestheticBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/KinestheticBtn.png"))); // NOI18N
        KinestheticBtn.setOpaque(false);
        KinestheticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KinestheticBtnActionPerformed(evt);
            }
        });
        KinestheticBtn.setBounds(100, 310, 110, 40);
        jLayeredPane1.add(KinestheticBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        takeTheQuizBtn.setText("Take the quiz");
        takeTheQuizBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                takeTheQuizBtnMouseClicked(evt);
            }
        });
        takeTheQuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeTheQuizBtnActionPerformed(evt);
            }
        });
        takeTheQuizBtn.setBounds(30, 370, 250, 40);
        jLayeredPane1.add(takeTheQuizBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        questionLbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        questionLbl.setForeground(new java.awt.Color(255, 255, 255));
        questionLbl.setText("What learning style are you?");
        questionLbl.setBounds(20, 160, 270, 30);
        jLayeredPane1.add(questionLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        videoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Video.png"))); // NOI18N
        videoBtn.setOpaque(false);
        videoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoBtnMouseClicked(evt);
            }
        });
        videoBtn.setBounds(210, 450, 80, 40);
        jLayeredPane1.add(videoBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        //Makes home button visible - brings back to home page
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        //Makes back button button visible - brings back to previous page
        this.setVisible(false);
        LearnHome myLearnH = new LearnHome();
        myLearnH.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    private void visualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualBtnActionPerformed
        //Makes visual button visible - brings you into visual page
        this.setVisible(false);
        Visual myVisual = new Visual();
        myVisual.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_visualBtnActionPerformed

    private void auditoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditoryBtnActionPerformed
        //Makes auditory button visible - brings you into auditory page
        this.setVisible(false);
        Auditory myAuditory = new Auditory();
        myAuditory.setVisible(true);
    }//GEN-LAST:event_auditoryBtnActionPerformed

    private void KinestheticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KinestheticBtnActionPerformed
        //Makes kinesthetic button visible - brings you into kinesthetic page
        this.setVisible(false);
        Kinesthetic myKinesthetic = new Kinesthetic();
        myKinesthetic.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_KinestheticBtnActionPerformed

    private void takeTheQuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeTheQuizBtnActionPerformed

    }//GEN-LAST:event_takeTheQuizBtnActionPerformed

    private void takeTheQuizBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_takeTheQuizBtnMouseClicked
        //Brings you to a vark learning quiz
        try {
            String URL = "http://www.vark-learn.com/english/page.asp?p=questionnaire";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_takeTheQuizBtnMouseClicked

    private void videoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoBtnMouseClicked
        //Brings you to a youtube learning style video
        try {
            String URL = "http://www.youtube.com/watch?v=tEpdFL1gYX0";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_videoBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton KinestheticBtn;
    private javax.swing.JButton auditoryBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel notesHeader;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JButton takeTheQuizBtn;
    private javax.swing.JButton videoBtn;
    private javax.swing.JButton visualBtn;
    // End of variables declaration//GEN-END:variables
}
