/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

/**
 *
 * @author James Cosgrave
 */
public class LearnContact extends javax.swing.JFrame {

    /**
     * Creates new form LearnContact
     */
    public LearnContact() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ContactDetailsLbl = new javax.swing.JLabel();
        tableLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ContactDetailsLbl.setFont(new java.awt.Font("Maiandra GD", 3, 20)); // NOI18N
        ContactDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        ContactDetailsLbl.setText("Contact Details");
        ContactDetailsLbl.setBounds(120, 100, 160, 25);
        jLayeredPane1.add(ContactDetailsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tableLbl.setText("<html>\n\n\n\n<style>\ntd\n{\nfont-weight:bold;\nbackground-color: #bff662;\nfont-size:10;\n}\n\n</style>\n\n\n<table  width=\"300\"  border=\"0\">\n<tr>\n<th style=\"background-color:white;\">Name</th>\n<th style=\"background-color:white;\">Job Title</th>\n<th style=\"background-color:white;\">Tel</th>\n<th style=\"background-color:white;\">E-mail</th>\n</tr>\n<tr>\n<td>Corrie Adams</td>\n<td>Student Support & Recreation Coordinator</td>\n<td>01-4498548</td>\n<td>corrie.adams@ncirl.ie </td>\n</tr>\n<tr>\n<td>Dr Leo Casey</td>\n<td>Director of Learning, Teaching, Research and Innovation</td>\n<td>01-6599210</td>\n<td>lcasey@ncirl.ie </td>\n</tr>\n<tr>\n<td>Catherine Elliott</td>\n<td>Learning Support Tutor</td>\n<td>01-6599208</td>\n<td>ce.elliott@ncirl.ie</td>\n</tr>\n<tr>\n<td>Dr Michael Goldrick</td>\n<td>Learning Support & Development Officer</td>\n<td>01-6599245</td>\n<td>ml.goldrick@ncirl.ie</td>\n</tr>\n</table>\n</html>");
        tableLbl.setBounds(0, 100, 300, 340);
        jLayeredPane1.add(tableLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN.setOpaque(false);
        BackBTN.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        BackBTN.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        //Makes home button visible - brings back to home page
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        //Makes back button button visible - brings back to previous page
        this.setVisible(false);
        LearnHome myLearnH = new LearnHome();
        myLearnH.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnContact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel ContactDetailsLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel tableLbl;
    // End of variables declaration//GEN-END:variables
}
