/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class LearnHome extends javax.swing.JFrame {

    /**
     * Creates new form LearnHome
     */
    public LearnHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        HomeBtn = new javax.swing.JButton();
        LearningHeaderLbl = new javax.swing.JLabel();
        NotesBtn = new javax.swing.JButton();
        classLocationBtn = new javax.swing.JButton();
        ContactBtn = new javax.swing.JButton();
        lectureTimesBtn = new javax.swing.JButton();
        bookingsBtn = new javax.swing.JButton();
        twitterBtn = new javax.swing.JButton();
        fbBtn = new javax.swing.JButton();
        gMailBtn = new javax.swing.JButton();
        SuBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        HomeBtn.setOpaque(false);
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        HomeBtn.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(HomeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LearningHeaderLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LearningHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        LearningHeaderLbl.setText("Learning");
        LearningHeaderLbl.setBounds(180, 100, 110, 40);
        jLayeredPane1.add(LearningHeaderLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NotesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/notesBTN.png"))); // NOI18N
        NotesBtn.setOpaque(false);
        NotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesBtnActionPerformed(evt);
            }
        });
        NotesBtn.setBounds(160, 150, 130, 60);
        jLayeredPane1.add(NotesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        classLocationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ClassBTN.png"))); // NOI18N
        classLocationBtn.setOpaque(false);
        classLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classLocationBtnActionPerformed(evt);
            }
        });
        classLocationBtn.setBounds(10, 220, 130, 60);
        jLayeredPane1.add(classLocationBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContactBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ContactBTN.png"))); // NOI18N
        ContactBtn.setOpaque(false);
        ContactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactBtnActionPerformed(evt);
            }
        });
        ContactBtn.setBounds(160, 220, 130, 60);
        jLayeredPane1.add(ContactBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lectureTimesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/TimesBTN.png"))); // NOI18N
        lectureTimesBtn.setOpaque(false);
        lectureTimesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureTimesBtnActionPerformed(evt);
            }
        });
        lectureTimesBtn.setBounds(10, 150, 130, 60);
        jLayeredPane1.add(lectureTimesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bookingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Bookings.png"))); // NOI18N
        bookingsBtn.setOpaque(false);
        bookingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsBtnActionPerformed(evt);
            }
        });
        bookingsBtn.setBounds(70, 290, 130, 60);
        jLayeredPane1.add(bookingsBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        twitterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/tw.png"))); // NOI18N
        twitterBtn.setOpaque(false);
        twitterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterBtnMouseClicked(evt);
            }
        });
        twitterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterBtnActionPerformed(evt);
            }
        });
        twitterBtn.setBounds(20, 430, 50, 50);
        jLayeredPane1.add(twitterBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fbBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/fb.png"))); // NOI18N
        fbBtn.setOpaque(false);
        fbBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbBtnMouseClicked(evt);
            }
        });
        fbBtn.setBounds(90, 430, 50, 50);
        jLayeredPane1.add(fbBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gMailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/goo.png"))); // NOI18N
        gMailBtn.setOpaque(false);
        gMailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gMailBtnMouseClicked(evt);
            }
        });
        gMailBtn.setBounds(160, 430, 50, 50);
        jLayeredPane1.add(gMailBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SU.png"))); // NOI18N
        SuBtn.setOpaque(false);
        SuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SuBtnMouseClicked(evt);
            }
        });
        SuBtn.setBounds(230, 430, 50, 50);
        jLayeredPane1.add(SuBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        //Makes home button visible - brings back to home page
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void NotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesBtnActionPerformed
        //Makes notes button visible - brings to notes page
        this.setVisible(false);
        LearnNotes myLearnN = new LearnNotes();
        myLearnN.setVisible(true);
    }//GEN-LAST:event_NotesBtnActionPerformed

    private void lectureTimesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureTimesBtnActionPerformed
        //Makes times button visible - brings to learning times page
        this.setVisible(false);
        LearnTimes myLearnT = new LearnTimes();
        myLearnT.setVisible(true);
    }//GEN-LAST:event_lectureTimesBtnActionPerformed

    private void classLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classLocationBtnActionPerformed
        //Makes location button visible - brings to learning location page
        this.setVisible(false);
        LearnLocation myLearnL = new LearnLocation();
        myLearnL.setVisible(true);    }//GEN-LAST:event_classLocationBtnActionPerformed

    private void ContactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactBtnActionPerformed
        //Makes contact button visible - brings to learning contact page
        this.setVisible(false);
        LearnContact myLearnC = new LearnContact();
        myLearnC.setVisible(true);    }//GEN-LAST:event_ContactBtnActionPerformed

    private void bookingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsBtnActionPerformed
        //Makes booking button visible - brings to bookings page
        this.setVisible(false);
        BookingG myBook = new BookingG();
        myBook.setVisible(true);

    }//GEN-LAST:event_bookingsBtnActionPerformed

    private void twitterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twitterBtnActionPerformed

    private void twitterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterBtnMouseClicked
        //Brings you to twitter page
        try {
            String URL = "www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_twitterBtnMouseClicked

    private void fbBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbBtnMouseClicked
        //Brings you to facebook page
        try {
            String URL = "www.facebook.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_fbBtnMouseClicked

    private void gMailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMailBtnMouseClicked
        //Brings you to gMail page
        try {
            String URL = "www.gmail.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_gMailBtnMouseClicked

    private void SuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuBtnMouseClicked
        //Brings you to SU page
        try {
            String URL = "www.ncisu.ie/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_SuBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContactBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel LearningHeaderLbl;
    private javax.swing.JButton NotesBtn;
    private javax.swing.JButton SuBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton bookingsBtn;
    private javax.swing.JButton classLocationBtn;
    private javax.swing.JButton fbBtn;
    private javax.swing.JButton gMailBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton lectureTimesBtn;
    private javax.swing.JButton twitterBtn;
    // End of variables declaration//GEN-END:variables
}
