/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

/**
 *
 * @author James Cosgrave
 */
public class Locations extends javax.swing.JFrame {

    /**
     * Creates new form Locations
     */
    public Locations() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        backBtn = new javax.swing.JButton();
        tableLbl = new javax.swing.JLabel();
        computingLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tableLbl.setText("<html>  <style> td { background-color:#bff662; font-weight:bold; font-size:12; } </style>  <table style=\"background-color:#;\" border=\"0\" cellspacing=\"5\" cellpadding=\"5\">  <tr align=\"center\" style=\" color:red;\"> <td style=\"  background-color:white; \" > Day </td> <td style=\"  background-color:white; \" > Room </td> <td style=\"  background-color:white; \" > Modulel </td> <td style=\"  background-color:white; \" > Lecturer </td>    </tr>  <tr align=\"center\" >  <td> Monday </td> <td> SCR1<br></br> LAB 3.03 </td> <td> Support Workshop </td> <td> Jonathan Meaney </td>  </tr>  <tr align=\"center\"  >  <td> Tuesday </td> <td> SCR1 LAB 3.03 </td> <td> Support Workshop </td> <td> Carole Sam Cogan </td>  </tr>  <tr align=\"center\">  <td> Wednesday </td> <td> LAB 3.03 </td> <td> Support Workshop </td> <td> Jonathan Meaney </td>  </tr>   <tr align=\"center\"  >  <td> Thursday </td> <td> LAB 3.03 SCR1 SCR1 </td> <td> Support Workshop </td> <td> Frances Sheridan Sam Cogan </td>  </tr>   </table>      </html> ");
        tableLbl.setBounds(0, 130, 300, 320);
        jLayeredPane1.add(tableLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        computingLbl.setForeground(new java.awt.Color(255, 255, 255));
        computingLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/LOC.gif"))); // NOI18N
        computingLbl.setBounds(70, 100, 230, 50);
        jLayeredPane1.add(computingLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel4.setBounds(0, 394, 230, 100);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, -10, 300, 520);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
this.setVisible(false);
ComputingHome myHome = new ComputingHome();
myHome.setVisible(true); 
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Locations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel computingLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel tableLbl;
    // End of variables declaration//GEN-END:variables
}
