/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class Log extends javax.swing.JFrame {

    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        NameLBL = new javax.swing.JLabel();
        StudentNumberLBL = new javax.swing.JLabel();
        CourseLBL = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        IDTF = new javax.swing.JTextField();
        CourseTF = new javax.swing.JTextField();
        NameTF = new javax.swing.JTextField();
        VewLog = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        LogBTN = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NameLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLBL.setForeground(new java.awt.Color(255, 255, 255));
        NameLBL.setText("Name:");
        NameLBL.setBounds(10, 170, 80, 20);
        jLayeredPane1.add(NameLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StudentNumberLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StudentNumberLBL.setForeground(new java.awt.Color(255, 255, 255));
        StudentNumberLBL.setText("Student ID:");
        StudentNumberLBL.setBounds(10, 270, 110, 20);
        jLayeredPane1.add(StudentNumberLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CourseLBL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CourseLBL.setForeground(new java.awt.Color(255, 255, 255));
        CourseLBL.setText("Course:");
        CourseLBL.setBounds(10, 220, 80, 20);
        jLayeredPane1.add(CourseLBL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.setBounds(10, 80, 50, 50);
        jLayeredPane1.add(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN.setOpaque(false);
        BackBTN.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        BackBTN.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        IDTF.setBounds(110, 270, 170, 30);
        jLayeredPane1.add(IDTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        CourseTF.setBounds(110, 220, 170, 30);
        jLayeredPane1.add(CourseTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        NameTF.setBounds(110, 170, 170, 30);
        jLayeredPane1.add(NameTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        VewLog.setOpaque(false);
        VewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VewLogActionPerformed(evt);
            }
        });
        VewLog.setBounds(210, 380, 80, 40);
        jLayeredPane1.add(VewLog, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ClearBTN.setOpaque(false);
        ClearBTN.setBounds(110, 380, 80, 40);
        jLayeredPane1.add(ClearBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LogBTN.setOpaque(false);
        LogBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBTNActionPerformed(evt);
            }
        });
        LogBTN.setBounds(10, 380, 80, 40);
        jLayeredPane1.add(LogBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        this.setVisible(false);
        ComputingHome myHome = new ComputingHome();
        myHome.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    private void LogBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBTNActionPerformed
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String name = NameTF.getText();
        String Course = CourseTF.getText();
        String StudentNumber = IDTF.getText();
        
        try {
            outFile = new File("LOG.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(name);
            bw.newLine();
            
            bw.write(Course);
            bw.newLine();
            
            bw.write(StudentNumber);
            bw.newLine();

            bw.close();
            
            JOptionPane.showMessageDialog(null, "Thank you for Loging in with our app");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
    }

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String name;
        String Course;
        String StudentNumber;
        
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("LOG.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            while (name != null) {
                JOptionPane.showMessageDialog(null, "Name: " + name);
                name = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }    }//GEN-LAST:event_LogBTNActionPerformed

    private void VewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VewLogActionPerformed

 String name;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("LOG.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            while (name != null) {
                JOptionPane.showMessageDialog(null, "Name: " + name);
                name = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_VewLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JLabel CourseLBL;
    private javax.swing.JTextField CourseTF;
    private javax.swing.JTextField IDTF;
    private javax.swing.JButton LogBTN;
    private javax.swing.JLabel NameLBL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel StudentNumberLBL;
    private javax.swing.JButton VewLog;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton jButton9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
