/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class MainHome extends javax.swing.JFrame {

    /**
     * Creates new form MainHome
     */
    public MainHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mathsBtn = new javax.swing.JButton();
        computingBtn = new javax.swing.JButton();
        disabilityBtn = new javax.swing.JButton();
        learningBtn = new javax.swing.JButton();
        facebookBtn = new javax.swing.JButton();
        twitterBtn = new javax.swing.JButton();
        gmailBtn = new javax.swing.JButton();
        nciBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 500));
        setResizable(false);

        mathsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Maths.png"))); // NOI18N
        mathsBtn.setOpaque(false);
        mathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsBtnActionPerformed(evt);
            }
        });
        mathsBtn.setBounds(10, 130, 130, 60);
        jLayeredPane1.add(mathsBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Computer.png"))); // NOI18N
        computingBtn.setOpaque(false);
        computingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computingBtnActionPerformed(evt);
            }
        });
        computingBtn.setBounds(160, 130, 130, 60);
        jLayeredPane1.add(computingBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Disa.png"))); // NOI18N
        disabilityBtn.setOpaque(false);
        disabilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityBtnActionPerformed(evt);
            }
        });
        disabilityBtn.setBounds(160, 200, 130, 60);
        jLayeredPane1.add(disabilityBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/learning.png"))); // NOI18N
        learningBtn.setOpaque(false);
        learningBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningBtnActionPerformed(evt);
            }
        });
        learningBtn.setBounds(10, 200, 130, 60);
        jLayeredPane1.add(learningBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        facebookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/fb.png"))); // NOI18N
        facebookBtn.setOpaque(false);
        facebookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookBtnMouseClicked(evt);
            }
        });
        facebookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookBtnActionPerformed(evt);
            }
        });
        facebookBtn.setBounds(10, 420, 50, 50);
        jLayeredPane1.add(facebookBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        twitterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/tw.png"))); // NOI18N
        twitterBtn.setOpaque(false);
        twitterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterBtnMouseClicked(evt);
            }
        });
        twitterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterBtnActionPerformed(evt);
            }
        });
        twitterBtn.setBounds(90, 420, 50, 50);
        jLayeredPane1.add(twitterBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gmailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/goo.png"))); // NOI18N
        gmailBtn.setOpaque(false);
        gmailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmailBtnMouseClicked(evt);
            }
        });
        gmailBtn.setBounds(170, 420, 50, 50);
        jLayeredPane1.add(gmailBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nciBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SU.png"))); // NOI18N
        nciBtn.setOpaque(false);
        nciBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nciBtnMouseClicked(evt);
            }
        });
        nciBtn.setBounds(240, 420, 50, 50);
        jLayeredPane1.add(nciBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computingBtnActionPerformed
this.setVisible(false);
ComputingHome myHome = new ComputingHome();
myHome.setVisible(true);

    }//GEN-LAST:event_computingBtnActionPerformed

    private void mathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsBtnActionPerformed
        this.setVisible(false);
        MathsHome myMaths = new MathsHome();
        myMaths.setVisible(true);
    }//GEN-LAST:event_mathsBtnActionPerformed

    private void disabilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityBtnActionPerformed
this.setVisible(false);
DisaHome myDHome = new DisaHome();
myDHome.setVisible(true);
    }//GEN-LAST:event_disabilityBtnActionPerformed

    private void learningBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningBtnActionPerformed
this.setVisible(false);
LearnHome myLearnH = new LearnHome();
myLearnH.setVisible(true);
    }//GEN-LAST:event_learningBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void facebookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_facebookBtnActionPerformed

    private void twitterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twitterBtnActionPerformed

    private void facebookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "http://www.facebook.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_facebookBtnMouseClicked

    private void twitterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "http://www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_twitterBtnMouseClicked

    private void gmailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?hl%3Den&ss=1&scc=1&ltmpl=default&ltmplcache=2&hl=en";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_gmailBtnMouseClicked

    private void nciBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nciBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "www.ncisu.ie";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_nciBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton computingBtn;
    private javax.swing.JButton disabilityBtn;
    private javax.swing.JButton facebookBtn;
    private javax.swing.JButton gmailBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton learningBtn;
    private javax.swing.JButton mathsBtn;
    private javax.swing.JButton nciBtn;
    private javax.swing.JButton twitterBtn;
    // End of variables declaration//GEN-END:variables
}
