/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class MathsNotes extends javax.swing.JFrame {

    /**
     * Creates new form MathsNotes
     */
    public MathsNotes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        deleteBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        notesTF = new java.awt.TextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        deleteBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/DeleteNotes.png"))); // NOI18N
        deleteBtn.setOpaque(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        deleteBtn.setBounds(160, 410, 140, 60);
        jLayeredPane1.add(deleteBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ViewNotes.png"))); // NOI18N
        viewBtn.setOpaque(false);
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        viewBtn.setBounds(160, 340, 140, 60);
        jLayeredPane1.add(viewBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        saveBtn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SaveNotes.png"))); // NOI18N
        saveBtn.setOpaque(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        saveBtn.setBounds(0, 340, 140, 60);
        jLayeredPane1.add(saveBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN.setText("Back");
        BackBTN.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN.setOpaque(false);
        BackBTN.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        BackBTN.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        notesTF.setBounds(10, 140, 280, 180);
        jLayeredPane1.add(notesTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Notes");
        jLabel4.setBounds(190, 90, 220, 50);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/bg5 (1).jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
       //Goes back to the main Home Page
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        //Goes back to the previous page
        this.setVisible(false);
        MathsHome myMaths = new MathsHome();
        myMaths.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Save Button saves the text into a file and stores it:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String notes = notesTF.getText();
        try {
            outFile = new File("Notes.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(notes);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Your Notes have been saved.");
        } catch (IOException e) {
            System.out.println("Error cannot write to Maths Notes: " + e);
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // Allows the user to view their notes as a file/JOptionPane Pop-up:
        String notes;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("notes.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            notes = br.readLine();
            while (notes != null) {
                JOptionPane.showMessageDialog(null, "Maths Notes: " + notes);
                notes = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Allows the user to delete their saved notes and start again:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        String notes = notesTF.getText();
        try {
            outFile = new File("Notes.txt");
            fw = new FileWriter(outFile, false);
            bw = new BufferedWriter(fw);

            bw.write(notes);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "Your Notes have been deleted.");
        } catch (IOException e) {
            System.out.println("Error cannot write to Maths Notes: " + e);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private java.awt.TextArea notesTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
