/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

/**
 *
 * @author James Cosgrave
 */
public class MathsTimes extends javax.swing.JFrame {

    /**
     * Creates new form MathsTimes
     */
    public MathsTimes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        table1Lbl = new javax.swing.JLabel();
        table2Lbl = new javax.swing.JLabel();
        table3Lbl = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        timesLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 90, 50, 40);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        table1Lbl.setText("<html>  <style>  td {  background-color:#bff662; border-bottom:2;   }    </style>  <table id=\"table\"   border=\"0\"   cellpadding=\"5\" cellspacing=\"5\">  <tr align=\"center\" >  <td style=\"background-color:white;\"> Day </td> <td style=\"background-color:white;\"> Time </td > <td style=\"background-color:white;\"> Room </td>  </tr>  <tr>  <td> Thursday </td> <td> 9am-11am </td> <td> 3.02 </td>  </tr>  <tr>  <td> Friday </td> <td> 9am-11am </td> <td> 3.08 </td>  </tr>     </table>     </html>");
        table1Lbl.setBounds(100, 100, 250, 140);
        jLayeredPane1.add(table1Lbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        table2Lbl.setText("<html>\n\n<style>\n\ntd\n{\n\nbackground-color:#bff662;\nborder-bottom:2;\n\n\n}\n\n\n\n</style>\n\n<table id=\"table\"   border=\"0\"   cellpadding=\"5\" cellspacing=\"5\">\n\n<tr align=\"center\" >\n\n<td style=\"background-color:white;\">\nDay\n</td>\n<td style=\"background-color:white;\">\nTime\n</td >\n<td style=\"background-color:white;\">\nRoom\n</td>\n\n</tr>\n\n<tr>\n\n<td>\nThursday\n</td>\n<td>\n1pm - 3pm\n</td>\n<td>\n3.02\n</td>\n\n</tr>\n\n<tr>\n\n<td>\nFriday\n</td>\n<td>\n11am - 1pm\n</td>\n<td>\n3.08\n</td>\n\n</tr>\n\n\n\n\n</table>\n\n\n\n\n</html>");
        table2Lbl.setBounds(100, 220, 210, 110);
        jLayeredPane1.add(table2Lbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        table3Lbl.setText("<html>\n\n<style>\n\ntd\n{\n\nbackground-color:#bff662;\nborder-bottom:2;\n\n\n}\n\n\n\n</style>\n\n<table id=\"table\"   border=\"0\"   cellpadding=\"5\" cellspacing=\"5\">\n\n<tr align=\"center\" >\n\n<td style=\"background-color:white;\">\nDay\n</td>\n<td style=\"background-color:white;\">\nTime\n</td >\n<td style=\"background-color:white;\">\nRoom\n</td>\n\n</tr>\n\n<tr>\n\n<td>\nThursday\n</td>\n<td>\n3pm - 5pm\n</td>\n<td>\n3.02\n</td>\n\n</tr>\n\n<tr>\n\n<td>\nFriday\n</td>\n<td>\n3pm - 5pm\n</td>\n<td>\n3.08\n</td>\n\n</tr>\n\n\n\n\n</table>\n\n\n\n\n</html>");
        table3Lbl.setBounds(100, 300, 240, 170);
        jLayeredPane1.add(table3Lbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("BAHAHR1:");
        label1.setBounds(0, 140, 80, 20);
        jLayeredPane1.add(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("HCBS2:");
        label2.setBounds(10, 250, 70, 20);
        jLayeredPane1.add(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label3.setBackground(new java.awt.Color(191, 246, 98));
        label3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("BAMTB1:");
        label3.setBounds(10, 350, 70, 20);
        jLayeredPane1.add(label3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        timesLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        timesLbl.setForeground(new java.awt.Color(255, 255, 255));
        timesLbl.setText("Lecture Times");
        timesLbl.setBounds(120, 70, 180, 40);
        jLayeredPane1.add(timesLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/bg5 (1).jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        MathsHome myMaths = new MathsHome();
        myMaths.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsTimes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel table1Lbl;
    private javax.swing.JLabel table2Lbl;
    private javax.swing.JLabel table3Lbl;
    private javax.swing.JLabel timesLbl;
    // End of variables declaration//GEN-END:variables
}
