/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class  MathsHome extends javax.swing.JFrame {

    /**
     * Creates new form MathsHome
     */
    public MathsHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainClass1 = new computingsupport.MainClass();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        emailBtn = new javax.swing.JButton();
        notesBtn = new javax.swing.JButton();
        contactBtn = new javax.swing.JButton();
        timeBtn = new javax.swing.JButton();
        locationBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        gmailBtn = new javax.swing.JButton();
        ncisuBtn = new javax.swing.JButton();
        twitterBtn = new javax.swing.JButton();
        facebookBtn = new javax.swing.JButton();
        mathsLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        emailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Send Email.png"))); // NOI18N
        emailBtn.setOpaque(false);
        emailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtnActionPerformed(evt);
            }
        });
        emailBtn.setBounds(20, 320, 250, 30);
        jLayeredPane1.add(emailBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        notesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/notesBTN.png"))); // NOI18N
        notesBtn.setOpaque(false);
        notesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesBtnActionPerformed(evt);
            }
        });
        notesBtn.setBounds(160, 140, 130, 60);
        jLayeredPane1.add(notesBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        contactBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ContactBTN.png"))); // NOI18N
        contactBtn.setOpaque(false);
        contactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBtnActionPerformed(evt);
            }
        });
        contactBtn.setBounds(160, 210, 130, 60);
        jLayeredPane1.add(contactBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        timeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/TimesBTN.png"))); // NOI18N
        timeBtn.setOpaque(false);
        timeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBtnActionPerformed(evt);
            }
        });
        timeBtn.setBounds(10, 140, 130, 60);
        jLayeredPane1.add(timeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        locationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ClassBTN.png"))); // NOI18N
        locationBtn.setOpaque(false);
        locationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBtnActionPerformed(evt);
            }
        });
        locationBtn.setBounds(10, 210, 130, 60);
        jLayeredPane1.add(locationBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 80, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gmailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/goo.png"))); // NOI18N
        gmailBtn.setOpaque(false);
        gmailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gmailBtnMouseClicked(evt);
            }
        });
        gmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailBtnActionPerformed(evt);
            }
        });
        gmailBtn.setBounds(150, 440, 50, 50);
        jLayeredPane1.add(gmailBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ncisuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/SU.png"))); // NOI18N
        ncisuBtn.setOpaque(false);
        ncisuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ncisuBtnMouseClicked(evt);
            }
        });
        ncisuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncisuBtnActionPerformed(evt);
            }
        });
        ncisuBtn.setBounds(80, 440, 50, 50);
        jLayeredPane1.add(ncisuBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        twitterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/tw.png"))); // NOI18N
        twitterBtn.setOpaque(false);
        twitterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterBtnMouseClicked(evt);
            }
        });
        twitterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterBtnActionPerformed(evt);
            }
        });
        twitterBtn.setBounds(10, 440, 50, 50);
        jLayeredPane1.add(twitterBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        facebookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/fb.png"))); // NOI18N
        facebookBtn.setOpaque(false);
        facebookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookBtnMouseClicked(evt);
            }
        });
        facebookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookBtnActionPerformed(evt);
            }
        });
        facebookBtn.setBounds(220, 440, 50, 50);
        jLayeredPane1.add(facebookBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        mathsLbl.setForeground(new java.awt.Color(255, 255, 255));
        mathsLbl.setText("Maths");
        mathsLbl.setBounds(180, 100, 180, 40);
        jLayeredPane1.add(mathsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/bg5 (1).jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void gmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailBtnActionPerformed

    private void ncisuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncisuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ncisuBtnActionPerformed

    private void twitterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterBtnActionPerformed
        // TODO add your handling code here:
        try {
            String URL = "www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_twitterBtnActionPerformed

    private void facebookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facebookBtnActionPerformed

    private void timeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBtnActionPerformed
        this.setVisible(false);
        MathsTimes myTimes = new MathsTimes();
        myTimes.setVisible(true);
    }//GEN-LAST:event_timeBtnActionPerformed

    private void contactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBtnActionPerformed
        this.setVisible(false);
        MathsContact myMContact = new MathsContact();
        myMContact.setVisible(true);
    }//GEN-LAST:event_contactBtnActionPerformed

    private void notesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesBtnActionPerformed
        this.setVisible(false);
        MathsNotes myMNotes = new MathsNotes();
        myMNotes.setVisible(true);
    }//GEN-LAST:event_notesBtnActionPerformed

    private void locationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBtnActionPerformed
        this.setVisible(false);
        MathsLocation myMLocation = new MathsLocation();
        myMLocation.setVisible(true);
    }//GEN-LAST:event_locationBtnActionPerformed

    private void emailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtnActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       MathsEmail myEmail = new MathsEmail();
       myEmail.setVisible(true);
       
       
    }//GEN-LAST:event_emailBtnActionPerformed

    private void twitterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "www.twitter.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_twitterBtnMouseClicked

    private void ncisuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ncisuBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "www.ncisu.ie";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_ncisuBtnMouseClicked

    private void gmailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gmailBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?hl%3Den&ss=1&scc=1&ltmpl=default&ltmplcache=2&hl=en";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_gmailBtnMouseClicked

    private void facebookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookBtnMouseClicked
        // TODO add your handling code here:
        try {
            String URL = "http://www.facebook.com";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_facebookBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathsHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton contactBtn;
    private javax.swing.JButton emailBtn;
    private javax.swing.JButton facebookBtn;
    private javax.swing.JButton gmailBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton locationBtn;
    private computingsupport.MainClass mainClass1;
    private javax.swing.JLabel mathsLbl;
    private javax.swing.JButton ncisuBtn;
    private javax.swing.JButton notesBtn;
    private javax.swing.JButton timeBtn;
    private javax.swing.JButton twitterBtn;
    // End of variables declaration//GEN-END:variables
}
