/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author James Cosgrave
 */
public class MultiMediaNotes extends javax.swing.JFrame {

    /**
     * Creates new form MultiMediaNotes
     */
    public MultiMediaNotes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        MMNotesLbl = new javax.swing.JLabel();
        HomeBTN = new javax.swing.JButton();
        multimediaLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        PDFBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MMNotesLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Multi.jpg"))); // NOI18N
        MMNotesLbl.setBounds(10, 120, 280, 320);
        jLayeredPane1.add(MMNotesLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        HomeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        HomeBTN.setOpaque(false);
        HomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBTNActionPerformed(evt);
            }
        });
        HomeBTN.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(HomeBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        multimediaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multimediaLbl.setForeground(new java.awt.Color(255, 255, 255));
        multimediaLbl.setText("Multimedia ");
        multimediaLbl.setBounds(200, 70, 180, 70);
        jLayeredPane1.add(multimediaLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBtn.setOpaque(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        BackBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PDFBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/PDF.png"))); // NOI18N
        PDFBtn.setOpaque(false);
        PDFBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFBtnActionPerformed(evt);
            }
        });
        PDFBtn.setBounds(210, 450, 80, 40);
        jLayeredPane1.add(PDFBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBTNActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_HomeBTNActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        this.setVisible(false);
        CompNotes myNotes = new CompNotes();
        myNotes.setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void PDFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFBtnActionPerformed

        // resourced this code fom Stack overflow
        try {
            File pdf = new File("C:\\Users\\James Cosgrave\\Documents\\NetBeansProjects\\ComputingSupport - Copy\\src\\computingsupport\\MM.pdf");
            Desktop.getDesktop().open(pdf);
        } catch (IOException ex) {
            Logger.getLogger(Programming.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PDFBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiMediaNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiMediaNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiMediaNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiMediaNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiMediaNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton HomeBTN;
    private javax.swing.JLabel MMNotesLbl;
    private javax.swing.JButton PDFBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel multimediaLbl;
    // End of variables declaration//GEN-END:variables
}
