/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class Programming extends javax.swing.JFrame {

    /**
     * Creates new form Programming
     */
    public Programming() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        programmingLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();
        PDFBtn = new javax.swing.JButton();
        VideosBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        programmingLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        programmingLbl.setForeground(new java.awt.Color(255, 255, 255));
        programmingLbl.setText("Programming");
        programmingLbl.setBounds(170, 80, 180, 70);
        jLayeredPane1.add(programmingLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Program2.jpg"))); // NOI18N
        imageLbl.setBounds(10, 130, 280, 310);
        jLayeredPane1.add(imageLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PDFBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/PDF.png"))); // NOI18N
        PDFBtn.setOpaque(false);
        PDFBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFBtnActionPerformed(evt);
            }
        });
        PDFBtn.setBounds(210, 450, 80, 40);
        jLayeredPane1.add(PDFBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        VideosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Video.png"))); // NOI18N
        VideosBtn.setOpaque(false);
        VideosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VideosBtnMouseClicked(evt);
            }
        });
        VideosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideosBtnActionPerformed(evt);
            }
        });
        VideosBtn.setBounds(110, 450, 80, 40);
        jLayeredPane1.add(VideosBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        CompNotes myNotes = new CompNotes();
        myNotes.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void PDFBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFBtnActionPerformed

        // resourced this code fom Stack overflow
        try {
            File pdf = new File("C:\\Users\\James Cosgrave\\Documents\\NetBeansProjects\\ComputingSupport - Copy\\src\\computingsupport\\OOP.pdf");
            Desktop.getDesktop().open(pdf);
        } catch (IOException ex) {
            Logger.getLogger(Programming.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PDFBtnActionPerformed

    private void VideosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideosBtnActionPerformed
    }//GEN-LAST:event_VideosBtnActionPerformed

    private void VideosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideosBtnMouseClicked


        try {
            String URL = "www.youtube.com/feed/UCtUpH8J1hPwknbP55T3Vung";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_VideosBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programming().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PDFBtn;
    private javax.swing.JButton VideosBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel programmingLbl;
    // End of variables declaration//GEN-END:variables
}
