package computingsupport;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 *
 */
public class Registration extends javax.swing.JFrame implements Serializable {
    
    private String firstName;
    private String Surname;
    private String Course;
    private String StudentNumber;
    private ArrayList<Register> aList;
    private int count;
    
    public Registration() {
        initComponents();
        setLocationRelativeTo(null);
        firstName = new String();
        Surname = new String();
        Course = new String();
        StudentNumber = new String();
        aList = new ArrayList<>();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        FirstNameTF = new javax.swing.JTextField();
        fnameLbl = new javax.swing.JLabel();
        surnameLbl = new javax.swing.JLabel();
        SurnameTF = new javax.swing.JTextField();
        StudentIdTF = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        CourseTF = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        AttendingBtn = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        ContactDetailsLbl = new javax.swing.JLabel();
        BgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 60, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FirstNameTF.setBounds(120, 160, 160, 30);
        jLayeredPane1.add(FirstNameTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fnameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnameLbl.setForeground(new java.awt.Color(255, 255, 255));
        fnameLbl.setText("First Name:");
        fnameLbl.setBounds(20, 160, 90, 22);
        jLayeredPane1.add(fnameLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        surnameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        surnameLbl.setForeground(new java.awt.Color(255, 255, 255));
        surnameLbl.setText("Surname:");
        surnameLbl.setBounds(20, 200, 90, 22);
        jLayeredPane1.add(surnameLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SurnameTF.setBounds(120, 200, 160, 30);
        jLayeredPane1.add(SurnameTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StudentIdTF.setBounds(120, 240, 160, 30);
        jLayeredPane1.add(StudentIdTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        idLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLbl.setForeground(new java.awt.Color(255, 255, 255));
        idLbl.setText("Student ID:");
        idLbl.setBounds(20, 240, 100, 22);
        jLayeredPane1.add(idLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        courseLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseLbl.setForeground(new java.awt.Color(255, 255, 255));
        courseLbl.setText("Course:");
        courseLbl.setBounds(20, 270, 90, 30);
        jLayeredPane1.add(courseLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CourseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseTFActionPerformed(evt);
            }
        });
        CourseTF.setBounds(120, 280, 160, 30);
        jLayeredPane1.add(CourseTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Clear.png"))); // NOI18N
        Clear.setOpaque(false);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.setBounds(110, 350, 80, 40);
        jLayeredPane1.add(Clear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ADD.png"))); // NOI18N
        Add.setOpaque(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Add.setBounds(10, 350, 80, 40);
        jLayeredPane1.add(Add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AttendingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Attending.png"))); // NOI18N
        AttendingBtn.setOpaque(false);
        AttendingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendingBtnActionPerformed(evt);
            }
        });
        AttendingBtn.setBounds(210, 350, 80, 40);
        jLayeredPane1.add(AttendingBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        BackBTN.setMaximumSize(new java.awt.Dimension(300, 500));
        BackBTN.setOpaque(false);
        BackBTN.setPreferredSize(new java.awt.Dimension(300, 500));
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        BackBTN.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(BackBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ContactDetailsLbl.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        ContactDetailsLbl.setForeground(new java.awt.Color(255, 255, 255));
        ContactDetailsLbl.setText("Registration");
        ContactDetailsLbl.setBounds(140, 110, 170, 30);
        jLayeredPane1.add(ContactDetailsLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        BgLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(BgLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CourseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseTFActionPerformed
    
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        
        
        firstName = FirstNameTF.getText();
        Surname = SurnameTF.getText();
        Course = CourseTF.getText();
        StudentNumber = StudentIdTF.getText();

        //create a new Question object
        Register r = new Register();

        //add contents of textfields to r
        r.setFirstName(firstName);
        r.setSurname(Surname);
        r.setCourse(Course);
        r.setStudentNumber(StudentNumber);
        
        aList.add(r);
        count++;



        /*
         firstName = FirstNameTF.getText();
         Surname = SurnameTF.getText();
         Course = CourseTF.getText();
         StudentNumber = StudentIdTF.getText();


         //add contents of textfields to r
         r.setFirstName(firstName);
         r.setSurname(Surname);
         r.setCourse(Course);
         r.setStudentNumber(StudentNumber);
         */
        
        
        // create file streams
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        //creste instaces of file streams
        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            JOptionPane.showMessageDialog(rootPane, "Registerd Successfully");
            
            oStream.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
        
    }
    
    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:  
    }//GEN-LAST:event_AddActionPerformed
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        
        FirstNameTF.setText("");
        SurnameTF.setText("");
        CourseTF.setText("");
        StudentIdTF.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed
    
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed
    
    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        this.setVisible(false);
        ComputingHome myHome = new ComputingHome();
        myHome.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed
    
    private void AttendingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendingBtnActionPerformed
        
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try {
            
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            /*
             Register a;
            
             a = (Register) oStream.readObject();
             */
            
            ArrayList<Register> xList;
            xList = (ArrayList<Register>) oStream.readObject();
            
            for (Register x : xList) {
                JOptionPane.showMessageDialog(null, " First Name: " + x.getFirstName() + "\n Surname: " + x.getSurname() + "\n Student Number: " + x.getStudentNumber() + "\n Course: " + x.getCourse());
                
            }
            
            oStream.close();
        }
         catch (IOException e) {
            System.out.println(e);
    }//GEN-LAST:event_AttendingBtnActionPerformed
         catch (ClassNotFoundException ex) {
            System.out.print(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                    
                    
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton AttendingBtn;
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel BgLbl;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel ContactDetailsLbl;
    private javax.swing.JTextField CourseTF;
    private javax.swing.JTextField FirstNameTF;
    private javax.swing.JTextField StudentIdTF;
    private javax.swing.JTextField SurnameTF;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel fnameLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel surnameLbl;
    // End of variables declaration//GEN-END:variables
}
