/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package computingsupport;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author James Cosgrave
 */
public class RequestNotes extends javax.swing.JFrame {

    private ArrayList<Request> aList;
    private String Module;
    private String Lecturer;
    private String Topic;
    private String Week;
    private String StudentID;
    private int count;

    public RequestNotes() {
        initComponents();
        setLocationRelativeTo(null);
        aList = new ArrayList<>();
        Module = new String();
        Lecturer = new String();
        Topic = new String();
        Week = new String();
        StudentID = new String();
        count = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        requestLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        moduleLbl = new javax.swing.JLabel();
        lecturerLbl = new javax.swing.JLabel();
        topicLbl = new javax.swing.JLabel();
        weekLbl = new javax.swing.JLabel();
        RequestBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        RequstedBTN = new javax.swing.JButton();
        LecturerTF = new javax.swing.JTextField();
        TopicTF = new javax.swing.JTextField();
        WeekTF = new javax.swing.JTextField();
        StudentTF = new javax.swing.JTextField();
        ModuleTF = new javax.swing.JTextField();
        backgroundLbl = new javax.swing.JLabel();

        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Home.png"))); // NOI18N
        homeBtn.setOpaque(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        homeBtn.setBounds(10, 50, 50, 50);
        jLayeredPane1.add(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Arrow.png"))); // NOI18N
        backBtn.setOpaque(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(10, 450, 80, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        requestLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestLbl.setText("Request Notes");
        requestLbl.setBounds(130, 100, 180, 30);
        jLayeredPane1.add(requestLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        idLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLbl.setForeground(new java.awt.Color(255, 255, 255));
        idLbl.setText("Student ID:");
        idLbl.setBounds(10, 310, 80, 30);
        jLayeredPane1.add(idLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        moduleLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moduleLbl.setForeground(new java.awt.Color(255, 255, 255));
        moduleLbl.setText("Module:");
        moduleLbl.setBounds(10, 150, 70, 30);
        jLayeredPane1.add(moduleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lecturerLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lecturerLbl.setForeground(new java.awt.Color(255, 255, 255));
        lecturerLbl.setText("Lecturer:");
        lecturerLbl.setBounds(10, 190, 70, 30);
        jLayeredPane1.add(lecturerLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        topicLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topicLbl.setForeground(new java.awt.Color(255, 255, 255));
        topicLbl.setText("Topic:");
        topicLbl.setBounds(10, 230, 70, 30);
        jLayeredPane1.add(topicLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        weekLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weekLbl.setForeground(new java.awt.Color(255, 255, 255));
        weekLbl.setText("Week:");
        weekLbl.setBounds(10, 270, 70, 30);
        jLayeredPane1.add(weekLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        RequestBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/ReqNotes.png"))); // NOI18N
        RequestBTN.setOpaque(false);
        RequestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestBTNActionPerformed(evt);
            }
        });
        RequestBTN.setBounds(10, 370, 80, 30);
        jLayeredPane1.add(RequestBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ClearBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/CancelNotes.png"))); // NOI18N
        ClearBTN.setOpaque(false);
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        ClearBTN.setBounds(110, 370, 80, 30);
        jLayeredPane1.add(ClearBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        RequstedBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Requsted.png"))); // NOI18N
        RequstedBTN.setOpaque(false);
        RequstedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequstedBTNActionPerformed(evt);
            }
        });
        RequstedBTN.setBounds(210, 370, 80, 30);
        jLayeredPane1.add(RequstedBTN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LecturerTF.setBounds(110, 190, 170, 30);
        jLayeredPane1.add(LecturerTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TopicTF.setBounds(110, 230, 170, 30);
        jLayeredPane1.add(TopicTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        WeekTF.setBounds(110, 270, 170, 30);
        jLayeredPane1.add(WeekTF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StudentTF.setBounds(110, 310, 170, 30);
        jLayeredPane1.add(StudentTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ModuleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleTFActionPerformed(evt);
            }
        });
        ModuleTF.setBounds(110, 150, 170, 30);
        jLayeredPane1.add(ModuleTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computingsupport/Layer 2.jpg"))); // NOI18N
        backgroundLbl.setBounds(0, 0, 300, 500);
        jLayeredPane1.add(backgroundLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        this.setVisible(false);
        MainHome myMain = new MainHome();
        myMain.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        CompNotes myNotes = new CompNotes();
        myNotes.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void ModuleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModuleTFActionPerformed

    private void RequestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestBTNActionPerformed

        Module = ModuleTF.getText();
        Lecturer = LecturerTF.getText();
        Topic = TopicTF.getText();
        Week = WeekTF.getText();
        StudentID = StudentTF.getText();

        Request r = new Request();

        r.setModule(Module);
        r.setLecturer(Lecturer);
        r.setTopic(Topic);
        r.setWeek(Week);
        r.setStudentID(StudentID);

        aList.add(r);
        count++;
    }//GEN-LAST:event_RequestBTNActionPerformed

    private void RequstedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequstedBTNActionPerformed

        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(rootPane, " Module: " + aList.get(i).getModule() + "\n\n Lecturer: " + aList.get(i).getLecturer() + "\n\n Topic: " + aList.get(i).getTopic() + "\n\n Week: " + aList.get(i).getWeek() + "\n\n Student ID:" + aList.get(i).getStudentID());
        }

    }//GEN-LAST:event_RequstedBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
        ModuleTF.setText("");
        LecturerTF.setText("");
        TopicTF.setText("");
        WeekTF.setText("");
        StudentTF.setText("");
    }//GEN-LAST:event_ClearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestNotes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBTN;
    private javax.swing.JTextField LecturerTF;
    private javax.swing.JTextField ModuleTF;
    private javax.swing.JButton RequestBTN;
    private javax.swing.JButton RequstedBTN;
    private javax.swing.JTextField StudentTF;
    private javax.swing.JTextField TopicTF;
    private javax.swing.JTextField WeekTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lecturerLbl;
    private javax.swing.JLabel moduleLbl;
    private javax.swing.JLabel requestLbl;
    private javax.swing.JLabel topicLbl;
    private javax.swing.JLabel weekLbl;
    // End of variables declaration//GEN-END:variables
}
